apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ingest-statistics-monitoring
  namespace: boson-team
spec:
  selector:
    matchLabels:
      app:  ingest-statistics-monitoring
  replicas: 1
  template:
    metadata:
      name: ingest-statistics-monitoring-01
      labels:
        app: ingest-statistics-monitoring
      namespace: boson-team
    spec:
      containers:
        - name: ingest-statistics-monitoring
          image: 'default-route-openshift-image-registry.apps.devops.advantagedp.org/boson-team/ingest-statistics-monitoring-prod1:1.0'
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: '1'
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi   
            ports:
              - name: 8080-tcp
                protocol: TCP
                port: 8080
                targetPort: 8080